### ISSUE TITLE
linker should support LIDATA (.obj record type 0xa2)

### ISSUE THREAD

**Issue by mateuszviste** [pts/owccdos#1]
Hello,

I am experimenting a little with DOSMC. It's a very impressive project that worked surprisingly well for my (simple) tests. But then I tried to use it to link an actual program and libraries I have compiled with Open Watcom 1.9. Unfortunately it ended with an error:

$ dosmc -bt=com deflang.obj sved.obj mdr/mdrs2023.lib svarlang/svarlngs.lib
dosmc-linker-com: fatal: unsupported obj record type: type=0xa2 size=9

Would you have some hint about what this "type 0xa2 unsupported record" is? Is there some Open Watcom flag that I should use when compiling OBJ files so they are compatible with DOSMC?

I am using the "trunk" version of DOSMC from github.

**Comment by gurok** [comment]
I can replicate this with a simple test case:

```
#include <dosmc.h>

int mydata[9] = {65};

void _start(void)
{
	putchar(mydata[0]);

	return;
}
```

Note: compiles fine if the size of the int array is less than 9 or the array is not initialised.

**Comment by pts** [comment]
Sorry for the late reply! Thank you for reporting this, especially for the C program and the varying of the array size. 0xa2 is the LIDATA record (see in https://www.fileformat.info/format/ms-obj/corion.htm) in the .obj file. Indeed, this feature is missing from the *dosmc* linker. I'll add it soon, so that initialized arrays of any size will work.

**Comment by pts** [comment]
Fixed in https://github.com/pts/dosmc/commit/7376777095cb731239b83a9bc59d70468057f5f5. Thank you for reporting this!
